name: Norminette Check

on:
  pull_request:

jobs:
  norm_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Norminette
        run: pip install norminette

      - name: Run Norminette
        run: norminette
      - name: Run Norminette
        run: norminette > norminette_output.txt || true

      - name: Upload Norminette output
        uses: actions/upload-artifact@v2
        with:
          name: norminette-output
          path: norminette_output.txt

